// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package zhengwei.netty.grpc.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zhengwei.netty.grpc.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_name = 1;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string real_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
