// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package zhengwei.netty.grpc.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zhengwei.netty.grpc.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   */
  String getUserName();
  /**
   * <code>string user_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
