// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package zhengwei.netty.grpc.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_StudentResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zhengwei_netty_grpc_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zhengwei_netty_grpc_proto_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\031zhengwei.netty.grpc.pro" +
      "to\"\036\n\tMyRequest\022\021\n\tuser_name\030\001 \001(\t\"\037\n\nMy" +
      "Response\022\021\n\treal_name\030\001 \001(\t\":\n\017StudentRe" +
      "sponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004cit" +
      "y\030\003 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 \001(\005\"Z" +
      "\n\023StudentResponseList\022C\n\017studentResponse" +
      "\030\001 \003(\0132*.zhengwei.netty.grpc.proto.Stude" +
      "ntResponse\"%\n\rStreamRequest\022\024\n\014request_i" +
      "nfo\030\001 \001(\t\"\'\n\016StreamResponse\022\025\n\rresponse_" +
      "info\030\001 \001(\t2\276\003\n\016StudentService\022d\n\025GetReal" +
      "NameByUserName\022$.zhengwei.netty.grpc.pro" +
      "to.MyRequest\032%.zhengwei.netty.grpc.proto" +
      ".MyResponse\022j\n\017GetStudentByAge\022).zhengwe" +
      "i.netty.grpc.proto.StudentRequest\032*.zhen" +
      "gwei.netty.grpc.proto.StudentResponse0\001\022" +
      "w\n\030GetStudentsWrapperByArgs\022).zhengwei.n" +
      "etty.grpc.proto.StudentRequest\032..zhengwe" +
      "i.netty.grpc.proto.StudentResponseList(\001" +
      "\022a\n\006BiTalk\022(.zhengwei.netty.grpc.proto.S" +
      "treamRequest\032).zhengwei.netty.grpc.proto" +
      ".StreamResponse(\0010\001B+\n\031zhengwei.netty.gr" +
      "pc.protoB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_zhengwei_netty_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zhengwei_netty_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_MyRequest_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_zhengwei_netty_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zhengwei_netty_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_MyResponse_descriptor,
        new java.lang.String[] { "RealName", });
    internal_static_zhengwei_netty_grpc_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_zhengwei_netty_grpc_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_zhengwei_netty_grpc_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_zhengwei_netty_grpc_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_zhengwei_netty_grpc_proto_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_zhengwei_netty_grpc_proto_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_StudentResponseList_descriptor,
        new java.lang.String[] { "StudentResponse", });
    internal_static_zhengwei_netty_grpc_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_zhengwei_netty_grpc_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_zhengwei_netty_grpc_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_zhengwei_netty_grpc_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zhengwei_netty_grpc_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
