// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package zhengwei.netty.grpc.proto;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zhengwei.netty.grpc.proto.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
