// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package zhengwei.netty.grpc.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:zhengwei.netty.grpc.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .zhengwei.netty.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<zhengwei.netty.grpc.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .zhengwei.netty.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  zhengwei.netty.grpc.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .zhengwei.netty.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .zhengwei.netty.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends zhengwei.netty.grpc.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .zhengwei.netty.grpc.proto.StudentResponse studentResponse = 1;</code>
   */
  zhengwei.netty.grpc.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
